import { Metadata } from "next";


export const metadata: Metadata = {
  title:{
    absolute:"",
    default:"Next.js tutorial oaoao",
    template:"%s | adasdas",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>1234</header>
        {children}
        <footer>9999</footer>
        </body>
    </html>
  )
}
